# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 30, 11, 0, 3, 955892, tzinfo=utc), max_length=100, unique=True, verbose_name=b'\xe5\xa7\x93'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 30, 11, 0, 10, 863678, tzinfo=utc), max_length=100, unique=True, verbose_name=b'\xe5\x90\x8d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98'),
        ),
    ]
