# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160615_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'\xe5\xa7\x93'),
        ),
    ]
